
development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  STRIPE_PUBLISHABLE_KEY=pk_test_MYZ2Xw1cH3YBeXOLfIT9h18z
